#!/usr/bin/env python3
"""KL-127a dual-backend PTW fault classification and A/D probes.

The 15 causes generated by the page-table walker are each exercised with two
different nonzero field selections on both QEMU and gem5. Instruction faults
repair the leaf in a cfx_ptw self-handler and retry with ``escape ...,0``;
data faults validate the frame and skip with ``escape ...,1``. Ten additional
probes read the actual L1/L2 PTE memory after super/normal read/write accesses,
including same-page read-then-write sequences that discriminate a stale
host-side translation cache and software-clear/re-access sequences for A/D.
"""

import os
import struct
import subprocess
import sys
import tempfile


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
QEMU = os.environ.get(
    "QEMU_DADAO",
    os.path.join(REPO, ".work", "source", "qemu", "build",
                 "qemu-system-dadao"))
GEM5_DIR = os.path.expanduser("~/DADAO-gem5")
GEM5 = os.environ.get(
    "GEM5_OPT", os.path.join(GEM5_DIR, "build", "DADAO", "gem5.opt"))
GEM5_CFG = os.environ.get(
    "GEM5_FS", os.path.join(GEM5_DIR, "tests", "dadao", "dadao_fs.py"))
EVIDENCE = os.path.join(REPO, ".work", "evidence", "kl127a-ptw-fault-ad")

sys.path.insert(0, HERE)
from build_test_binary import load_reg, write_rrii, UNIMP_ENCODING  # noqa: E402


ROM_BASE = 0x00100000
RAM_BASE = 0x80000000
FAULT_OFFSET = 0x500
HANDLER_OFFSET = 0x800
PASS = 42
FAIL = 0x9A

CFX_PTW = 4
CFX_POWER = 63
OP_CFX2RD = 0x72
OP_CFX2RC = 0x73
OP_ESCAPE = 0x77
OP_HALT = 0x00
OP_JUMP_R = 0x65
OP_LDO = 0x33
OP_STO = 0x3B
OP_STT = 0x3A
OP_MISC = 0x10
MISC_ORR = 0x09
MISC_XOR = 0x0A
OP_CSZ = 0x22

PTW_PERM_CG = 8
PTW_ENABLE_RC = 8
PTW_PTBR_CG = 9
PTW_PTHI_CG = 10
PTW_PAHI_CG = 11

MODE_USER = 0
MODE_JAIL = 1
MODE_SUPV = 2
MODE_HYPV = 3

CAUSES = {
    "NUPERM": 1 << 8,
    "NJPERM": 1 << 9,
    "NSPERM": 1 << 10,
    "NHPERM": 1 << 11,
    "NXPERM": 1 << 12,
    "NWPERM": 1 << 13,
    "NRPERM": 1 << 14,
    "IGPTRAP": 1 << 16,
    "ISPTRAP": 1 << 17,
    "IGPFTRAP": 1 << 18,
    "ISPFTRAP": 1 << 19,
    "DGPTRAP": 1 << 20,
    "DSPTRAP": 1 << 21,
    "DGPFTRAP": 1 << 22,
    "DSPFTRAP": 1 << 23,
}

MODE_CASES = {
    "NUPERM": MODE_USER,
    "NJPERM": MODE_JAIL,
    "NSPERM": MODE_SUPV,
    "NHPERM": MODE_HYPV,
}

FAULT_CASES = [
    ("NUPERM", "mode", "read"),
    ("NJPERM", "mode", "read"),
    ("NSPERM", "mode", "read"),
    ("NHPERM", "mode", "read"),
    ("NXPERM", "permission", "exec"),
    ("NWPERM", "permission", "write"),
    ("NRPERM", "permission", "read"),
    ("IGPTRAP", "normal-present", "exec"),
    ("ISPTRAP", "super-present", "exec"),
    ("IGPFTRAP", "normal-fragment", "exec"),
    ("ISPFTRAP", "super-fragment", "exec"),
    ("DGPTRAP", "normal-present", "read"),
    ("DSPTRAP", "super-present", "read"),
    ("DGPFTRAP", "normal-fragment", "read"),
    ("DSPFTRAP", "super-fragment", "read"),
]


def write_crrr(out, op, cfxcode, cg, rc, rd):
    word = ((op & 0xFF) << 24) | ((cfxcode & 0x3F) << 18) | \
        ((cg & 0x3F) << 12) | ((rc & 0x3F) << 6) | (rd & 0x3F)
    out.extend(struct.pack(">I", word))


def write_ciii(out, op, cfxcode, imm18):
    word = ((op & 0xFF) << 24) | ((cfxcode & 0x3F) << 18) | \
        (imm18 & 0x3FFFF)
    out.extend(struct.pack(">I", word))


def write_orrr(out, minor, dst, lhs, rhs):
    word = (OP_MISC << 24) | ((minor & 0x3F) << 18) | \
        ((dst & 0x3F) << 12) | ((lhs & 0x3F) << 6) | (rhs & 0x3F)
    out.extend(struct.pack(">I", word))


def emit_halt(out, rd):
    out.extend(struct.pack(">I", (OP_HALT << 24) | (rd << 18)))


def emit_result(out, mismatch_rd=30):
    load_reg(out, "rd", 26, PASS)
    load_reg(out, "rd", 27, FAIL)
    word = (OP_CSZ << 24) | (mismatch_rd << 18) | \
        (28 << 12) | (26 << 6) | 27
    out.extend(struct.pack(">I", word))
    emit_halt(out, 28)


def emit_value_check(out, actual_rd, expected):
    load_reg(out, "rd", 4, expected)
    write_orrr(out, MISC_XOR, 5, actual_rd, 4)
    write_orrr(out, MISC_ORR, 30, 30, 5)


def cfx_write(out, cfxcode, cg, rc, value):
    load_reg(out, "rd", 2, value)
    write_crrr(out, OP_CFX2RC, cfxcode, cg, rc, 2)


def pad_to(out, offset):
    if len(out) > offset:
        raise AssertionError(f"probe overflow: {len(out):#x} > {offset:#x}")
    while len(out) < offset:
        out.extend(struct.pack(">I", UNIMP_ENCODING))


def permission_bit(access):
    return {"read": 1 << 7, "write": 1 << 6, "exec": 1 << 5}[access]


def field_values(variant, superpage):
    index = 5 + variant
    l1_index = 9 + variant * 2
    l2_index = 13 + variant * 2
    # Fetch retries stay in the shared 0x84000000 super leaf. Other cases
    # may still select a different fragment through their fixture builder.
    fragment = 1 if superpage else 3 + variant
    inner_offset = 0x2000 + variant * 0x1000
    if superpage:
        offset = (fragment << 26) | inner_offset
        va = (index << 42) | (l1_index << 29) | offset
        pa = 0x80000000 | offset
    else:
        offset = (l2_index << 16) | (fragment << 13) | \
            (0x100 + variant * 0x80)
        va = (index << 42) | (l1_index << 29) | offset
        pa = 0x80300000 | (offset & 0xFFFF)
    return {
        "index": index,
        "l1_index": l1_index,
        "l2_index": l2_index,
        "fragment": fragment,
        "offset": offset,
        "va": va,
        "pa": pa,
        "l1_base": 0x80010000,
        "l2_base": 0x80100000,
    }


def put_qword(image, pa, value):
    offset = pa - RAM_BASE
    image[offset:offset + 8] = struct.pack(">Q", value)


def build_fault_fixture(cause_name, failure, access, variant):
    superpage = failure.startswith("super")
    if failure == "permission":
        superpage = variant == 0
    fields = field_values(variant, superpage)
    image = bytearray(0x110000)
    l1_addr = fields["l1_base"] + fields["l1_index"] * 8
    l2_addr = fields["l2_base"] + fields["l2_index"] * 8
    perms = permission_bit(access)
    super_leaf = (1 << (56 + fields["fragment"])) | \
        (0x8000 << 16) | perms | 0x3
    normal_l1 = (0x8010 << 16) | 0x1
    normal_leaf = (1 << (56 + fields["fragment"])) | \
        (0x8030 << 16) | perms | 0x1
    fix_addr = None
    corrected = None

    if failure == "mode":
        # No PTE is consulted; distinct index/L1/offset fields still prove
        # both variants report the original nonzero VA.
        pass
    elif failure == "super-present":
        put_qword(image, l1_addr, 0x2)
        fix_addr, corrected = l1_addr, super_leaf
    elif failure == "super-fragment":
        missing = super_leaf & ~(0xFF << 56)
        put_qword(image, l1_addr, missing)
        fix_addr, corrected = l1_addr, super_leaf
    elif failure == "normal-present":
        if variant == 0:
            put_qword(image, l1_addr, 0)
            put_qword(image, l2_addr, normal_leaf)
            fix_addr, corrected = l1_addr, normal_l1
        else:
            put_qword(image, l1_addr, normal_l1)
            put_qword(image, l2_addr, 0)
            fix_addr, corrected = l2_addr, normal_leaf
    elif failure == "normal-fragment":
        put_qword(image, l1_addr, normal_l1)
        missing = normal_leaf & ~(0xFF << 56)
        put_qword(image, l2_addr, missing)
        fix_addr, corrected = l2_addr, normal_leaf
    elif failure == "permission":
        other_perms = {
            "exec": (1 << 7) | (1 << 6),
            "write": (1 << 7) | (1 << 5),
            "read": (1 << 6) | (1 << 5),
        }[access]
        if superpage:
            denied = (super_leaf & ~((1 << 7) | (1 << 6) | (1 << 5))) | \
                other_perms
            put_qword(image, l1_addr, denied)
            fix_addr, corrected = l1_addr, denied | perms
        else:
            put_qword(image, l1_addr, normal_l1)
            denied = (normal_leaf & ~((1 << 7) | (1 << 6) | (1 << 5))) | \
                other_perms
            put_qword(image, l2_addr, denied)
            fix_addr, corrected = l2_addr, denied | perms
    else:
        raise AssertionError(f"unknown failure {failure}")

    fields.update({
        "image": bytes(image),
        "superpage": superpage,
        "fix_addr": fix_addr,
        "corrected": corrected,
        "cause": CAUSES[cause_name],
        "access": access,
        "mode": MODE_CASES.get(cause_name, MODE_HYPV),
    })
    return fields


def emit_mode_switch(out, mode):
    if mode == MODE_HYPV:
        load_reg(out, "rb", 3, ROM_BASE + FAULT_OFFSET)
        write_rrii(out, OP_JUMP_R, 3, 0, 0)
        return
    cfx_write(out, CFX_POWER, 5, 0, mode)
    cfx_write(out, CFX_POWER, 5, 1, 0xFFFFFFFFFFFFFFFF)
    cfx_write(out, CFX_POWER, 5, 3, ROM_BASE + FAULT_OFFSET)
    cfx_write(out, CFX_POWER, 5, 5, CFX_POWER)
    write_ciii(out, OP_ESCAPE, CFX_POWER, 0)


def emit_leaf_code(out, physical):
    code = bytearray()
    emit_result(code)
    for offset in range(0, len(code), 4):
        word = int.from_bytes(code[offset:offset + 4], "big")
        load_reg(out, "rd", 2, word)
        load_reg(out, "rb", 3, physical + offset)
        write_rrii(out, OP_STT, 2, 3, 0)


def emit_handler(out, fields, cause_ip, cause_info, retry):
    pad_to(out, HANDLER_OFFSET)
    for rc, expected in (
            (2, fields["cause"]), (3, cause_ip), (4, cause_info)):
        write_crrr(out, OP_CFX2RD, CFX_PTW, 5, rc, 3)
        emit_value_check(out, 3, expected)
    if retry:
        load_reg(out, "rd", 2, fields["corrected"])
        load_reg(out, "rb", 3, fields["fix_addr"])
        write_rrii(out, OP_STO, 2, 3, 0)
    write_ciii(out, OP_ESCAPE, CFX_PTW, 0 if retry else 1)


def gen_fault_probe(cause_name, failure, access, variant):
    fields = build_fault_fixture(cause_name, failure, access, variant)
    out = bytearray()
    load_reg(out, "rd", 30, 0)
    cfx_write(out, CFX_PTW, 2, 10, ROM_BASE + HANDLER_OFFSET)
    cfx_write(out, CFX_PTW, PTW_PTBR_CG, fields["index"],
              fields["l1_base"] >> 16)
    cfx_write(out, CFX_PTW, PTW_PTHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PAHI_CG, fields["index"], 0)
    if failure == "mode":
        cfx_write(out, CFX_PTW, PTW_PERM_CG, fields["mode"], 1)
    cfx_write(out, CFX_PTW, PTW_PERM_CG, PTW_ENABLE_RC,
              1 << fields["index"])

    retry = access == "exec"
    if retry:
        emit_leaf_code(out, fields["pa"])
    emit_mode_switch(out, fields["mode"])
    pad_to(out, FAULT_OFFSET)

    if access == "exec":
        cause_ip = fields["va"]
        cause_info = fields["va"]
        load_reg(out, "rb", 3, fields["va"])
        write_rrii(out, OP_JUMP_R, 3, 0, 0)
    else:
        load_reg(out, "rb", 3, fields["va"])
        if access == "write":
            load_reg(out, "rd", 2, 0x127A127A127A127A)
        cause_ip = ROM_BASE + len(out)
        cause_info = fields["va"]
        op = OP_STO if access == "write" else OP_LDO
        write_rrii(out, op, 2 if access == "write" else 3, 3, 0)
        emit_result(out)

    emit_handler(out, fields, cause_ip, cause_info, retry)
    return bytes(out), fields["image"], {
        "cause_ip": cause_ip,
        "cause_info": cause_info,
        "fields": fields,
    }


def build_ad_fixture(kind, access):
    superpage = kind == "super"
    fields = field_values(0 if superpage else 1, superpage)
    image = bytearray(0x110000)
    l1_addr = fields["l1_base"] + fields["l1_index"] * 8
    l2_addr = fields["l2_base"] + fields["l2_index"] * 8
    perms = ((1 << 7) | (1 << 6)) if access == "read-write" else \
        permission_bit(access)
    if superpage:
        pte = (1 << (56 + fields["fragment"])) | \
            (0x8000 << 16) | perms | 0x3
        pte_addr = l1_addr
        put_qword(image, pte_addr, pte)
    else:
        put_qword(image, l1_addr, (0x8010 << 16) | 0x1)
        pte = (1 << (56 + fields["fragment"])) | \
            (0x8030 << 16) | perms | 0x1
        pte_addr = l2_addr
        put_qword(image, pte_addr, pte)
    fields.update({
        "image": bytes(image),
        "pte": pte,
        "pte_addr": pte_addr,
        "expected": pte | (1 << 3) |
            ((1 << 2) if access in ("write", "read-write") else 0),
    })
    return fields


def gen_ad_probe(kind, access):
    fields = build_ad_fixture(kind, access)
    out = bytearray()
    load_reg(out, "rd", 30, 0)
    if access == "read":
        load_reg(out, "rd", 2, 0xADAD000000000127)
        load_reg(out, "rb", 3, fields["pa"])
        write_rrii(out, OP_STO, 2, 3, 0)
    cfx_write(out, CFX_PTW, PTW_PTBR_CG, fields["index"],
              fields["l1_base"] >> 16)
    cfx_write(out, CFX_PTW, PTW_PTHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PAHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PERM_CG, PTW_ENABLE_RC,
              1 << fields["index"])
    load_reg(out, "rb", 3, fields["va"])
    if access == "write":
        load_reg(out, "rd", 2, 0xD1D1D1D10000127A)
        write_rrii(out, OP_STO, 2, 3, 0)
    else:
        write_rrii(out, OP_LDO, 3, 3, 0)
    load_reg(out, "rb", 3, fields["pte_addr"])
    write_rrii(out, OP_LDO, 3, 3, 0)
    emit_value_check(out, 3, fields["expected"])
    emit_result(out)
    return bytes(out), fields["image"], fields


def gen_ad_read_write_probe(kind):
    fields = build_ad_fixture(kind, "read-write")
    out = bytearray()
    load_reg(out, "rd", 30, 0)
    cfx_write(out, CFX_PTW, PTW_PTBR_CG, fields["index"],
              fields["l1_base"] >> 16)
    cfx_write(out, CFX_PTW, PTW_PTHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PAHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PERM_CG, PTW_ENABLE_RC,
              1 << fields["index"])
    load_reg(out, "rb", 3, fields["va"])
    write_rrii(out, OP_LDO, 3, 3, 0)
    load_reg(out, "rd", 2, 0xD1D1D1D10000127A)
    write_rrii(out, OP_STO, 2, 3, 0)
    load_reg(out, "rb", 3, fields["pte_addr"])
    write_rrii(out, OP_LDO, 3, 3, 0)
    emit_value_check(out, 3, fields["expected"])
    emit_result(out)
    return bytes(out), fields["image"], fields


def gen_ad_clear_retry_probe(kind, access):
    fields = build_ad_fixture(kind, access)
    out = bytearray()
    load_reg(out, "rd", 30, 0)
    cfx_write(out, CFX_PTW, PTW_PTBR_CG, fields["index"],
              fields["l1_base"] >> 16)
    cfx_write(out, CFX_PTW, PTW_PTHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PAHI_CG, fields["index"], 0)
    cfx_write(out, CFX_PTW, PTW_PERM_CG, PTW_ENABLE_RC,
              1 << fields["index"])

    load_reg(out, "rb", 3, fields["va"])
    if access == "write":
        load_reg(out, "rd", 2, 0xD1D1D1D10000127A)
        write_rrii(out, OP_STO, 2, 3, 0)
        reset_pte = fields["pte"] | (1 << 3)
    else:
        write_rrii(out, OP_LDO, 3, 3, 0)
        reset_pte = fields["pte"]

    # Modify the real PTE through its identity-mapped physical address.
    load_reg(out, "rd", 2, reset_pte)
    load_reg(out, "rb", 3, fields["pte_addr"])
    write_rrii(out, OP_STO, 2, 3, 0)

    load_reg(out, "rb", 3, fields["va"])
    if access == "write":
        load_reg(out, "rd", 2, 0xD2D2D2D20000127A)
        write_rrii(out, OP_STO, 2, 3, 0)
    else:
        write_rrii(out, OP_LDO, 3, 3, 0)

    load_reg(out, "rb", 3, fields["pte_addr"])
    write_rrii(out, OP_LDO, 3, 3, 0)
    emit_value_check(out, 3, fields["expected"])
    emit_result(out)
    return bytes(out), fields["image"], fields


def run_backend(name, backend, rom_path, ram_path):
    if backend == "qemu":
        command = [
            QEMU, "-M", "dadao-m1", "-bios", rom_path,
            "-kernel", ram_path, "-display", "none", "-serial", "none",
            "-d", "int,mmu",
        ]
    else:
        command = [
            GEM5, "--outdir=" + tempfile.mkdtemp(
                prefix=f"gem5_kl127a_{name}_"),
            GEM5_CFG, rom_path, "--data-image", ram_path,
        ]
    result = subprocess.run(
        command, capture_output=True, timeout=60, text=True)
    with open(os.path.join(EVIDENCE, f"{name}-{backend}.log"), "w") as stream:
        stream.write("=== command ===\n" + " ".join(command))
        stream.write("\n=== stdout ===\n" + result.stdout)
        stream.write("\n=== stderr ===\n" + result.stderr)
    assert result.returncode == PASS, (
        f"{name}/{backend} rc={result.returncode}\n{result.stderr}")
    if backend == "gem5":
        assert f"SIM_END: halt code={PASS}" in result.stdout, result.stdout


def run(name, rom, ram):
    os.makedirs(EVIDENCE, exist_ok=True)
    rom_path = os.path.join(EVIDENCE, name + ".bin")
    ram_path = os.path.join(EVIDENCE, name + "-ram.bin")
    with open(rom_path, "wb") as stream:
        stream.write(rom)
    with open(ram_path, "wb") as stream:
        stream.write(ram)
    for backend in ("qemu", "gem5"):
        run_backend(name, backend, rom_path, ram_path)
    print(f"{name}: qemu=42 gem5=42")


def main():
    fault_count = 0
    for cause_name, failure, access in FAULT_CASES:
        for variant in (0, 1):
            rom, ram, evidence = gen_fault_probe(
                cause_name, failure, access, variant)
            fields = evidence["fields"]
            assert fields["index"] != 0 and fields["l1_index"] != 0
            if not fields["superpage"]:
                assert fields["l2_index"] != 0 and fields["fragment"] != 0
            run(f"fault-{cause_name.lower()}-v{variant}", rom, ram)
            fault_count += 1

    ad_count = 0
    for kind in ("super", "normal"):
        for access in ("read", "write"):
            rom, ram, _ = gen_ad_probe(kind, access)
            run(f"ad-{kind}-{access}", rom, ram)
            ad_count += 1
        rom, ram, _ = gen_ad_read_write_probe(kind)
        run(f"ad-{kind}-read-write", rom, ram)
        ad_count += 1
        for access in ("read", "write"):
            rom, ram, _ = gen_ad_clear_retry_probe(kind, access)
            run(f"ad-{kind}-clear-{access}", rom, ram)
            ad_count += 1

    print(f"PASS: {fault_count} fault probes "
          f"(15 walker causes x 2 variants) + {ad_count} A/D probes; "
          "QEMU=gem5; retry+skip self-handler")


if __name__ == "__main__":
    main()
